default: &default
  adapter: postgresql
  host: 127.0.0.1
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  username: chenhanting
  password: password

development:
  <<: *default
  database: hao_dev

test:
  <<: *default
  database: hao_test

production:
  <<: *default
  database: hao_prd